### ISSUE TITLE
No “Genomes” directory in FTP Site

### ISSUE THREAD

**Issue by Xuyifei-NAU** [BV-BRC/BV-BRC-Docs#80]
Hi everyone,

I want to download data for a large number of genomes, then I followed the tutorials at https://www.bv-brc.org/docs/quick_references/ftp.html. However, I found that there was no “Genomes” directory in FTP Site [ftp://ftp.bvbrc.org/], so the solution provided could not be used.

 ```for i in `cat genome_list`; do wget -qN "ftp://ftp.bvbrc.org/genomes/$i/$i.fna";done```

Could you provide us with directions where genomes were accessible to download with the above shell script?
![image](https://user-images.githubusercontent.com/35768429/210160286-7eb19bb7-ac32-4c3c-8a7b-c02da89a5f4d.png)

Thanks!
Yifei

**Comment by chris-c-thomas** [comment]
Hi Yifei,

Because the genomes directory is so large it's currently disabled from loading in the ftp GUI and might possibly not even show up in the listing depending on which client you are using. For instance, Cyberduck shows the directory but will not open it, while FileZilla will not display the directory at all (which is what I think you're seeing in the screenshot you posted).

I'll make the documentation a little more clear but creating a file with your desired `genome_id` and running a quick script for what files you want is likely the easiest way to bulk download right now. Let me give you an example of an approach.

<img width="890" alt="Screenshot 2023-01-07 at 2 22 42 PM" src="https://user-images.githubusercontent.com/22353987/211169093-3a188572-ca2f-4402-8b51-00f2a0010973.png">

Here I have just a small example of 5 genomes. You can download the table in your preferred format and copy the ids into a file we will call `genome_list` (it can be anything, you'll just need to reference the correct file name in an upcoming command)

<img width="527" alt="Screenshot 2023-01-07 at 2 26 57 PM" src="https://user-images.githubusercontent.com/22353987/211169214-ce533ce0-fb1c-434d-a723-c4de7f5cb2b0.png">

<img width="300" alt="Screenshot 2023-01-07 at 2 35 05 PM" src="https://user-images.githubusercontent.com/22353987/211169432-82ee9529-5040-4041-a205-ea4334bc400d.png">

Now that we have the genome ids in our file we can run:

```
for i in `cat genome_list`; do wget -qN "ftp://ftp.bvbrc.org/genomes/$i/$i.fna";
done
```

If you named your file something else make sure to update that above. This will grab the .fna file for each genome. If you are interested in a different file type you can replace `.fna` with the desired file type extension you want above.

I now have the 5 files requested downloaded:

<img width="931" alt="Screenshot 2023-01-07 at 2 45 50 PM" src="https://user-images.githubusercontent.com/22353987/211169718-4202918a-047a-414a-b3c2-266974e52e78.png">

Please let us know if you have any other questions or need more assistance. Again, I'll work to make some parts of the documentation a little clearer.

**Comment by Xuyifei-NAU** [comment]
Hi Thomas,

Thanks for the detailed documentation, it is very helpful, I have just successfully downloaded some genome files following the script you provided.

I tried to download files using the script in the tutorial before asking for help on Github, but it was always unsuccessful, so I used FileZilla to visit the FTP site and check if the file existed. I am sorry that I did not consider the display problem.

Thanks again for your reply and help.

Yifei

**Comment by chris-c-thomas** [comment]
@Xuyifei-NAU you are very welcome. The documentation was not very clear regarding the lacking visibility of the directory.

Please don't hesitate to reach out any time on here or email help@bv-brc.org

I'm marking this as completed now.
